project:
  type: book

execute:
  freeze: auto

book:
  title: "Civil Procedure"
  subtitle: "An Open-Source Casebook"
  author:
  - name: Eric M. Fink
    email: efink@elon.edu
    affiliations:
      - name: Elon University School of Law
        address: 201 North Greene Street
        city: Greensboro
        state: NC
        postal-code: 27278
  date: September 2025
  date-format: MMMM YYYY
  license: "CC BY NC SA"
  downloads: [pdf]
  url: https://www.emfink.net/CivProBook
  repo-url: https://github.com/EricMFink/CivProBook
  repo-actions: issue
  search: true
  reader-mode: true
  sidebar:
    style: "docked"
  chapters:
    - index.qmd
    - 01-Front/epigraph.qmd
    - 01-Front/preface.qmd
    - part: "Content"
      chapters:
        - 02-Main/chap1.qmd
        - 02-Main/chap2.qmd
        - 03-Back/references.qmd
        - 03-Back/ack.qmd
        - 03-Back/colophon.qmd

bibliography: CivProBook.yaml
csl: casebook-bibliography.csl

format:
  bookup-html:
    header-includes: |
      <link rel="stylesheet" href="https://use.typekit.net/viv2jun.css">    
    backgroundcolor: FloralWhite
    sidebarbackgroundcolor: FloralWhite
    mainfont: "athelas"
    toc: true
    toc-depth: 3
    toc-location: left
    number-sections: true
    number-depth: 3
    reference-location: margin
    citation-location: document