project:
    type: tufte
book:
  open-graph: true
  site-url: https://www.emfink.org/CivProBook
  repo-url: https://github.com/EricMFink/CivProBook
  repo-actions: [issue]
  title: "Civil Procedure"
  subtitle: "An Open-Source Casebook"
  title-short: Civil Procedure # title-short is used in the pdf head
  output-file: CivProBook # outputs: docs/CivProBook.pdf
  author: Eric M. Fink
  date: September 2025
  date-format: MMMM, YYYY
  license: "CC BY NC SA"
  downloads: [pdf]
  chapters:
    - index.qmd
    - 01-Front/titlepage.qmd
    - 01-Front/license.tex
    - 01-Front/epigraph.tex
    - 01-Front/preface.qmd
    - part: "Content"
      chapters:
        - 02-Main/chap1.qmd
        - 02-Main/chap2.qmd
        - 03-Back/references.qmd
        - 03-Back/ack.qmd
        - 03-Back/colophon.qmd
bibliography: CivProBook.yaml
csl: casebook.csl
reference-location: margin
citation-location: margin

format:
  html:
    header-includes: |
      <link rel="stylesheet" href="https://use.typekit.net/viv2jun.css">
    mainfont: athelas
    toc: true
    toc-depth: 3
    number-sections: true
    number-depth: 3
    css: casebook.css
