project:
    type: tufte
book:
  open-graph: true
  site-url: https://www.emfink.org/CivProBook
  repo-url: https://github.com/EricMFink/CivProBook
  repo-actions: [issue]
  title: "Civil Procedure"
  subtitle: "An Open-Source Casebook"
  title-short: Civil Procedure # title-short is used in the pdf head
  output-file: CivProBook # outputs: docs/CivProBook.pdf
  author: Eric M. Fink
  date: September 2025
  date-format: MMMM, YYYY
  license: "CC BY NC SA"
  downloads: [pdf]
  chapters:
    - index.qmd
    - 01-Front/titlepage.qmd
    - 01-Front/license.tex
    - 01-Front/epigraph.tex
    - 01-Front/preface.qmd
    - part: "Content"
      chapters:
        - 02-Main/chap1.qmd
        - 02-Main/chap2.qmd
        - 03-Back/references.qmd
        - 03-Back/ack.qmd
        - 03-Back/colophon.qmd
bibliography: CivProBook.yaml
csl: casebook.csl

format:
  html:
    header-includes: |
      <link rel="stylesheet" href="https://use.typekit.net/viv2jun.css">    
    page-layout: full
    reference-location: margin
    citation-location: margin
    title-block-style: none
    linkcolor: HopkinsBlue
    backgroundcolor: FloralWhite
    sidebarbackgroundcolor: FloralWhite
    default-image-extension: svg
    mainfont: "athelas"
    toc: true
    toc-depth: 4
    toc-location: left
    toc-title: "Contents"
    number-sections: true
    number-depth: 3
    css: casebook.css
  pdf:
    reference-location: margin
    citation-location: margin
    fig-cap-location: bottom
    documentclass: tufte-book
    classoption: [sfsidenotes]
    number-sections: true
    number-depth: 3
    format-resources:
      - tufte-book.cls
      - tufte-common.def
      - tufte.bst
    template-partials: # replaces
      - "partials/title.tex"
      - "partials/before-body.tex"
    include-in-header: #adds
      - "partials/in-header.tex"
      - "partials/definitions.tex"
    include-after-body: #adds
      - "partials/after-body.tex"
    toc-depth: 4
    toc-title: "Contents"
    indent: 0px
    mainfont: "athelas"
    sansfont: "Adelle Sans"
    sansfontoptions: "Scale=MatchUppercase"
    default-image-extension: png